cusvar: server02

server:
  port: 12222
#spring.application.name= CONFIG-CENTER

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
   web:
    exposure:
      include: '*'
   health:
    show-details:  ALWAYS

eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
#一定要设置为true或者不写，否则会出现unavailable-replicas
eureka:
  client:
   fetch-registry: true
   register-with-eureka: true #一定要设置为true或者不写，否则会出现unavailable-replicas
   register-with-eureka: false #该应用为注册中心，不向自己注册自己
   fetch-registry: false #是否从euruka服务器获取注册信息
   service-url:
    defaultZone: http://server2:12222/eureka/
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
data:
  env: localhost-dev-editserver02
  user:
    username: fengzheng-devserver02
    password: password-dev