cusvar: server01

server:
  port: 12345
#spring.application.name= CONFIG-CENTER

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true #一定要设置为true或者不写，否则会出现unavailable-replicas
    service-url:
      defaultZone: http://server2:12222/eureka/
data:
 env: localhost-dev-editserver01update1
 user:
  username: fengzheng-devserver01update1
  password: password-dev