server:
  port: 10001
#单节点eureka server配置
#eureka.client.serviceUrl.defaultZone = http://localhost:12345/eureka/
#多节点eureka server配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:12345/eureka/,http://server2:12222/eureka/

#spring.application.name= SPRING-CLIENT-01

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/managerdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  rabbitmq:
    host: 10.56.112.91
    port: 5672
    username: guest
    password: guest

#测试数据
data:
 env: localhost-dev2-edit
 user:
  username: fengzheng-dev2
  password: password-dev2
