cusvar: server02

server:
  port: 12222
#spring.application.name= CONFIG-CENTER

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true #一定要设置为true或者不写，否则会出现unavailable-replicas
    service-url:
      defaultZone: http://server1:12345/eureka/

data:
 env: localhost-dev-editserver02update1
 user:
  username: fengzheng-devserver02update1
  password: password-dev