cusvar: server01

server:
  port: 12345
#spring.application.name= CONFIG-CENTER

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    health:
#      show-details:  ALWAYS

eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
#一定要设置为true或者不写，否则会出现unavailable-replicas
  client:
    fetch-registry: true
    register-with-eureka: true #一定要设置为true或者不写，否则会出现unavailable-replicas
    service-url:
      defaultZone: http://server2:12222/eureka/
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
data:
 env: localhost-dev-editserver01update1
 user:
  username: fengzheng-devserver01update1
  password: password-dev