server:
  port: 10002
#单节点eureka server配置
#eureka.client.serviceUrl.defaultZone = http://localhost:12345/eureka/
#多节点eureka server配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:12345/eureka/,http://server2:12222/eureka/

#spring.application.name= SPRING-CLIENT-01

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/managerdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

#测试数据
data:
 env: localhost-prod-edit
 user:
  username: fengzheng-prod
  password: password-prod
